### PR TITLE
Added 2 junk science sites

### PR DESCRIPTION
**Pull request by tomatell**
- fairewinds.org: It is run by Arnie Gundersen who spreads
scare-mongering news about Fukushima without proper expert knowledge.

- enenews.com: ENENEWS launched its site a week after Japan's Greate
Tohoku Earthquake. The most of headlines are citing scare-mongering
headlines about the Fukushima nuclear accident with fabricated
information.

### CODE REVIEW

**Comment by tomlutzenberger** [comment]
FYI: This is a forked repo ;)
Sites have to be submitted using [this form](http://www.opensources.co/submissions/new?).

**Comment by tomatell** [comment]
Hi Tom,

Something is wrong with the form. See the attached screenshot.

**Comment by tomatell** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by tomlutzenberger** [comment]
Then you may want to open an issue at https://github.com/BigMcLargeHuge/opensources/issues .
But a forked repo is definitely the wrong place to do so.

**Pull request closed without merging**
